spring.application.name=budget-tracker

# PostgreSQLへの接続設定 (localhostの5342ポートにある budgetdb に接続)
spring.datasource.url=jdbc:postgresql://localhost:5432/budgetdb
spring.datasource.driver-class-name=org.postgresql.Driver

# 【要確認】PostgreSQLのユーザー名とパスワード
# インストール時に変更していなければユーザー名は postgres です。パスワードはご自身のものに変えてください。
spring.datasource.username=postgres
spring.datasource.password=994287yN

# pgAdmin側でテーブルを作ったので、Java側では自動生成を「none（何もしない）」にします
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 画面のポート番号
server.port=8081